Improve permissions and give Laurent permission to the DOI list
docker-library/meta-scripts pull request #103
Opened 2024-12-20 15:02 UTC by LaurentGoderre

TODO: Add the `@docker-library/maintainers` group to this repo

2025-01-22 21:28 UTC, tianon requested changes
Sorry for missing this one! :see_no_evil:

2025-01-22 21:28 UTC, tianon commented on .github/CODEOWNERS
> +/doi.jq             @LaurentGoderre  @docker-library/maintainers
A lot of extra whitespace here :sweat_smile: (we usually only do this when we're lining up columns in multiple lines)

```suggestion
/doi.jq  @LaurentGoderre  @docker-library/maintainers
```

Also, note GitHub's :no_entry: icon -- we're missing newline-at-EOF :eyes:

2025-01-23 14:41 UTC, LaurentGoderre commented on .github/CODEOWNERS
> +/doi.jq             @LaurentGoderre  @docker-library/maintainers
Done!

2025-01-23 18:25 UTC, tianon approved these changes

2025-01-23 18:25 UTC, merged